interface questionListItem {
  id: number;
  question: string;
  answerA: string;
  answerB: string;
  answerC: string;
  correctAnswer: string;
  difficulty: number;
}

export const questionList: Array<questionListItem> = [
  {
    id: 0,
    question:
      "Kome je prvome Wilson predstavio Četrnaest točaka u siječnju 1918. godine?",
    answerA: "američkom Kongresu",
    answerB: "europskim premijerima",
    answerC: "Ligi naroda",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 1,
    question:
      "Wilson je tvrdio da mirovni ugovori moraju biti javni. Koji je ugovor ovom točkom poništen?",
    answerA: "Talijanski ugovor",
    answerB: "Versailleski ugovor",
    answerC: "Londonski ugovor",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 2,
    question:
      "Četrnaesta točka navodi osnivanje Lige naroda. Koje je godine Liga osnovana?",
    answerA: "1918.",
    answerB: "1919.",
    answerC: "1917.",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 3,
    question:
      "Woodrow Wilson je smatrao da svaka država mora imati dovoljno vojne snage samo...",
    answerA: "za potrebe nužne obrane",
    answerB: "koliko žele",
    answerC: "onoliko koliko je imaju i susjedne države",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 4,
    question: "Koja je država obnovljena nakon više od stotinu godina?",
    answerA: "Poljska",
    answerB: "Belgija",
    answerC: "Rumunjska",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 5,
    question: "Tko ne pripada velikoj četvorici?",
    answerA: "Woodrow Wilson",
    answerB: "Vladimir Iljič Uljanov",
    answerC: "David Lloyd George",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 6,
    question: "Koje je godine vođena Pariška mirovna konferencija?",
    answerA: "1919./1920.",
    answerB: "1920.",
    answerC: "1919.",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 7,
    question: "Rusija je pozvana na Parišku mirovnu konferenciju.",
    answerA: "Djelomično",
    answerB: "Točno",
    answerC: "Netočno",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 8,
    question: "Poražene države su na Pariškoj mirovnoj konferenciji smjele...",
    answerA: "utjecati na mirovne uvjete",
    answerB: "ući u EU",
    answerC: "prihvatiti odluke pobjednica",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 9,
    question:
      "Što je od navedenog odrednica Versailleskog ugovora (mirovnog ugovora za Njemačku)?",
    answerA: "Plaćanje ratne odštete",
    answerB: "Njemačka je postala republika",
    answerC: "Veći teritorij",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 10,
    question: "Woodrow Wilson je smatrao da je Versailleski ugovor...",
    answerA: "nepravedan",
    answerB: "pravedan",
    answerC: "adekvatan",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 11,
    question:
      "Mađarska je mirovni ugovor potpisala u _______, a Austrija u ________.",
    answerA: "Saint-Germainu, Trianonu",
    answerB: "Beču, Dubrovniku",
    answerC: "Trianonu, Saint-Germainu",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 12,
    question:
      "Koliko je novih država nastalo kao posljedica Pariške mirovne konferencije?",
    answerA: "6",
    answerB: "9",
    answerC: "7",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 13,
    question:
      "Koja se britanska kolonija prva uspjela izboriti da sama zastupa svoje interese nakon Prvog svjetskog rata?",
    answerA: "Južna Afrika",
    answerB: "Novi Zeland",
    answerC: "Kanada",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 14,
    question:
      "Koja je država nakon Prvog svjetskog rata zauzela područja Osmanskog Carstva u Maloj Aziji?",
    answerA: "Mađarska",
    answerB: "Francuska",
    answerC: "Grčka",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 15,
    question: "Koji je grad postao glavnim gradom Turske za vrijeme Atatürka?",
    answerA: "Ankara",
    answerB: "Istanbul",
    answerC: "Atena",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 16,
    question:
      "Koje je godine Turska prestala biti monarhija i postala republikom?",
    answerA: "1923.",
    answerB: "1922.",
    answerC: "1921.",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 17,
    question: "Što je Njemačka postala nakon Prvog svjetskog rata?",
    answerA: "monarhija",
    answerB: "republika",
    answerC: "totalitarna država",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 18,
    question:
      "Koja je revolucija osnažila komunističke težnje u Weimarskoj Republici?",
    answerA: "Travanjska",
    answerB: "Oktobarska",
    answerC: "Februarska",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 19,
    question: "Nastanak koje države je freikorps krvavo ugušio?",
    answerA: "Čehoslovačke",
    answerB: "Bavarske Sovjetske Republike",
    answerC: "Mađarske Sovjetske Republike",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 20,
    question:
      "Koja vojska nije bila dio gušenja nastanka Mađarske Sovjetske Republike?",
    answerA: "vojska Kraljevstva SHS",
    answerB: "rumunjska vojska",
    answerC: "turska vojska",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 21,
    question:
      "Što je bio jedan od mnogih razloga za početak Drugog svjetskog rata?",
    answerA: "Zadovoljstvo Italije",
    answerB: "nestabilnost Njemačke",
    answerC: "zadovoljstvo Rusije",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 22,
    question: "Početkom 19. st. pravo glasa na izborima imali su...",
    answerA: "bogati",
    answerB: "odrasli muškarci",
    answerC: "žene",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 23,
    question:
      "________ je prva država u kojoj su žene dobile pravo glasa, _________ godine.",
    answerA: "Novi Zeland, 1893.",
    answerB: "Francuska, 1945.",
    answerC: "Ujedinjeno Kraljevstvo, 1918.",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 24,
    question: "U SAD-u se referendumi provode na razini...",
    answerA: "saveznih država",
    answerB: "glavnih gradova",
    answerC: "cjelokupne države",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 25,
    question: "U kojoj je državi i danas često referendumsko odlučivanje?",
    answerA: "Hrvatskoj",
    answerB: "Francuskoj",
    answerC: "Švicarskoj",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 26,
    question: "Predsjednik Hrvatske rat može proglasiti...",
    answerA: "uz odobrenje Sabora",
    answerB: "sam",
    answerC: "uz odobrenje EU",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 27,
    question: "Sabor je dio trodiobe vlasti, odnosno on ima _________ ovlasti.",
    answerA: "sudske",
    answerB: "zakonodavne",
    answerC: "izvršne",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 28,
    question:
      "Ustav RH isključivo navodi da se nikad više ne smije dogoditi stvaranje Jugoslavije.",
    answerA: "Djelomično",
    answerB: "Točno",
    answerC: "Netočno",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 29,
    question: "Sudska vlast mora biti...",
    answerA: "neovisna",
    answerB: "odgovorna Vladi (izvršna vlast)",
    answerC: "odgovorna Saboru (zakonodavna vlast)",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 30,
    question:
      "Demokracija se u 20. st. naziva i liberalnom. Što je od navedenog liberalna ideja?",
    answerA: "smanjeno pravo glasa",
    answerB: "cenzura tiska",
    answerC: "sekularizacija",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 31,
    question:
      "Najmoćnije liberalne demokracije međuratnog razdoblja bile su ujedno i kolonijale sile.",
    answerA: "Točno",
    answerB: "Netočno",
    answerC: "Djelomično",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 32,
    question: "U diktaturi se trodioba vlasti nalazi u rukama...",
    answerA: "građana",
    answerB: "pojedinca",
    answerC: "parlamenta",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 33,
    question: "Diktatura je nasljedna, stoga se ne razlikuje od apsolutizma.",
    answerA: "Točno",
    answerB: "Djelomično",
    answerC: "Netočno",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 34,
    question: "Što opisuje totalitarne sustave?",
    answerA: "sloboda građana",
    answerB: "sloboda tiska",
    answerC: "policijski teror",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 35,
    question: "Rusija je do 1917. godine bila...",
    answerA: "monarhija",
    answerB: "federacija",
    answerC: "demokratska država",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 36,
    question:
      "Što se od navedenog često smatra najvećim razlogom pobune ruskog stanovništva 1917. godine?",
    answerA: "vlada obitelji Romanov",
    answerB: "Staljin",
    answerC: "Lenjin",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 37,
    question:
      "Pobuna u Rusiji dogodila se i 1905. godine. Protiv koje države je tada Rusija izgubila u ratu?",
    answerA: "Tajvana",
    answerB: "Kine",
    answerC: "Japana",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 38,
    question:
      "U glavnom gradu Rusije, ________, počinje Februarska revolucija 1917. godine protiv vladavine Nikole II.",
    answerA: "Moskvi",
    answerB: "Petrogradu",
    answerC: "Nikolagradu",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 39,
    question:
      "Ruski parlament (Duma) izabire privremenu vladu. Njen prvi predsjednik bio je…",
    answerA: "Vladimir Iljič",
    answerB: "Georgij Lvov",
    answerC: "Josif Visarionovič",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 40,
    question:
      "Privremena vlada donijela je odluku o izlasku Rusije iz Prvog svjetskog rata.",
    answerA: "Točno",
    answerB: "Nema dovoljno podataka",
    answerC: "Netočno",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 41,
    question:
      "Socijaldemokratska stranka Rusije dijelila se na dvije frakcije. Tko je bio brojniji 1917. godine?",
    answerA: "boljševici",
    answerB: "jednak broj",
    answerC: "menjševici",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 42,
    question:
      "Boljševici su zastupali ideje Karla Marxa. Oni su ustvari ruski komunisti.",
    answerA: "Točno",
    answerB: "Netočno",
    answerC: "Točno i Netočno",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 43,
    question:
      "Lenjin je od 1905. živio je u Švicarskoj. Tko mu je (navodno) omogućio povratak u Petrograd?",
    answerA: "Njemačka",
    answerB: "Osmansko Carstvo",
    answerC: "Francuska",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 44,
    question:
      "Oktobarskom revolucijom boljševici zauzimaju Zimski dvorac i svrgavaju privremenu vladu.",
    answerA: "Točno",
    answerB: "Netočno",
    answerC: "Djelomično",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 45,
    question:
      "Boljševici su na izborima za Ustavotvornu skupštinu 1918. ________.",
    answerA: "dobili parcijalnu vlast",
    answerB: "pobijedili",
    answerC: "izgubili",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 46,
    question:
      "Vojska je stala na stranu boljševika i pomogla im uvesti diktaturu.",
    answerA: "Točno",
    answerB: "Netočno",
    answerC: "Djelomično",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 47,
    question:
      "Tko se usprotivio boljševičkoj diktaturi zbog gubitka statusa i bogatstva?",
    answerA: "siromaštvo",
    answerB: "radnici",
    answerC: "poduzetnici",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 48,
    question:
      "Stvaraju se dvije vojne frakcije - crvena i bijela. Koja je vojska pomagala bijelima, na koncu bezuspješno?",
    answerA: "francuska",
    answerB: "španjolska",
    answerC: "kineska",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 49,
    question: "Obitelj Romanov preživjela je 1918. godinu.",
    answerA: "preživila je 1919.",
    answerB: "Netočno",
    answerC: "Točno",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 50,
    question:
      "Lenjin umire 1924. godine. Koliko je godina prije njegove smrti osnovan SSSR?",
    answerA: "1",
    answerB: "3",
    answerC: "2",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 51,
    question:
      "Vlast nakon Lenjina preuzima Staljin. Trockog je ____ smijenio s dužnosti, ____ protjerao iz države i ____ dao ubiti.",
    answerA: "1925., 1929., 1940.",
    answerB: "1940., 1925., 1929.",
    answerC: "1929., 1925., 1940.",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 52,
    question:
      "Italija nakon Prvog svjetskog rata doživljava gospodarsku krizu.",
    answerA: "Djelomično",
    answerB: "Točno",
    answerC: "Netočno",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 53,
    question:
      "Italiju su nakon rata potresali prosvjedi i štrajkovi. U tim okolnostima fašisti su u početku bili _______.",
    answerA: "neuspješni",
    answerB: "uspješni",
    answerC: "polovno uspješni",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 54,
    question:
      "Uz fašiste, u Italiji djeluju nasilni odredi bivših vojnika pod nazivom...",
    answerA: "arditi",
    answerB: "freikorps",
    answerC: "spartakovci",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 55,
    question:
      "Pripadnici fašističkih odreda, po uzoru na svoje odore, nose naziv...",
    answerA: "bijelokošuljaši",
    answerB: "crvenokošuljaši",
    answerC: "crnokošuljaši",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 56,
    question:
      "Fašisti su svoj teror prvotno usmjerili protiv _______ kojima su, između ostaloga, provaljivali u kuće.",
    answerA: "kapitalista",
    answerB: "socijalista",
    answerC: "anarhista",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 57,
    question:
      "Glavna težnja fašista bilo je od Italije učiniti svjetsku velesilu, odnosno provesti...",
    answerA: "rođendansku proslavu",
    answerB: "jačanje vojske",
    answerC: "referendum",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 58,
    question:
      "U Njemačkoj se, kao i u Italiji, javlja želja za statusom velesile. Koja je stranka to posebno isticala?",
    answerA: "Nacionalsocijalistička stranka",
    answerB: "Nacionalsocijalistička radnička stranka",
    answerC: "Nacionalistička stranka",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 59,
    question:
      "Hitler je _____ godine pokušao izvesti puč u gradu ______, po uzoru na marš na Rim.",
    answerA: "1923., Münchenu",
    answerB: "1921., Bremenu",
    answerC: "1922., Frankfurtu",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 60,
    question:
      "Hitler je 1933. godine pozvan sastaviti _______, što mu je olakšalo uvođenje diktature.",
    answerA: "Sabor",
    answerB: "Referendum",
    answerC: "Vladu",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 61,
    question:
      "Hitler je svoj politički program izložio u knjizi Mein Kampf. Zagovarao je antisemitizam, odnosno...",
    answerA: "mržnju prema Slavenima",
    answerB: "mržnju prema Rusima",
    answerC: "mržnju prema Židovima",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 62,
    question: "Koji je glavni cilj kolonijalnih sila 19. i 20. stoljeća?",
    answerA: "iskorištavanje prirodnih bogatstava",
    answerB: "iskorištavanje radne snage domaćeg stanovništva",
    answerC: "sve od navedenog",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 63,
    question: "Kako su kolonijalne sile opravdavale svoju kolonizaciju?",
    answerA: "smatrale su da je domaće stanovništvo nesposobno da vlada samo ",
    answerB: "donirali su im novac",
    answerC: "željele su pomoći domaćem stanovništvu",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 64,
    question:
      "U doba britanske kolonizacije, osnovno školstvo u Indiji vodilo se na _______ jeziku.",
    answerA: "indijskom (tj. nekom od domaćih jezika)",
    answerB: "engleskom i indijskom",
    answerC: "engleskom",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 65,
    question:
      "Najnadareniji indijski učenici mogli su školovanje nastaviti u Ujedinjenom Kraljevstvu.",
    answerA: "Točno",
    answerB: "Djelomično",
    answerC: "Netočno",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 66,
    question:
      "Godine _____ osnovana je Kongresna stranka, a ______ njezino vodstvo preuzima Mahatma Gandhi.",
    answerA: "1901. / 1883.",
    answerB: "1885 / 1920.",
    answerC: "1850 / 1915.",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 67,
    question:
      "Najstariji oblik nenasilnog otpora u Indiji nosi naziv Swadeshi. Kako se taj pojam može prevesti? ",
    answerA: "svoji u tuđoj zemlji",
    answerB: "svoji u svojoj zemlji",
    answerC: "svoji u njegovoj zemlji",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 68,
    question: "Na što su poticali Swadeshijanci?",
    answerA: "kupnju domaćih proizvoda",
    answerB: "stranu proizvodnju",
    answerC: "uvoz dobara",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 69,
    question: "Što se moglo dogoditi pristašama Swadeshi pokreta?",
    answerA: "gubitak posla",
    answerB: "zapošljavanje",
    answerC: "dobivanje promocije",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 70,
    question: "Koji je pisac stao uz pokret za indijsku neovisnost?",
    answerA: "Raranath Tagro",
    answerB: "Rabinadrth Tagore",
    answerC: "Rabindranath Tagore",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 71,
    question: "Koje je godine Indija dobila samostalnost?",
    answerA: "1947.",
    answerB: "1945.",
    answerC: "1946.",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 72,
    question: "Navedi točno trajanje japanskog Taisho razdoblja.",
    answerA: "1914. - 1918.",
    answerB: "1912. - 1926.",
    answerC: "1926. - 1932",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 73,
    question: "Godine 1926. na vlast u Japanu dolazi car Hirohito.",
    answerA: "Djelomično",
    answerB: "Netočno",
    answerC: "Točno",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 74,
    question:
      "Koje su godine mladi japanski časnici pokušali izvesti državni udar?",
    answerA: "1932.",
    answerB: "1931.",
    answerC: "1930.",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 75,
    question:
      "Japan je posebice želio zauzeti kineski teritorij označen na karti. Koji?",
    answerA: "Guangdong",
    answerB: "Xinjiang",
    answerC: "Mandžuriju",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 76,
    question: "Stoljeće poniženja za Kinu bilo je od polovice 19. st. do...",
    answerA: "1953.",
    answerB: "1949.",
    answerC: "1947.",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 77,
    question: "Kina je do 1912. godine bila _______, a zatim ________.",
    answerA: "federacija, republika",
    answerB: "carstvo, republika",
    answerC: "monarhija, carstvo",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 78,
    question: "Kako se zvala stranka koju je Sun Yat-sen osnovao?",
    answerA: "Chubanpin",
    answerB: "Kuomintang",
    answerC: "Zhengque",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 79,
    question: "Komunistička partija Kine nastaje...",
    answerA: "1920.",
    answerB: "1921.",
    answerC: "1922.",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 80,
    question:
      "Nakon pobjede nad Japanom, kineski komunisti 1949. godine osnivaju...",
    answerA: "Kineska Narodna Republika",
    answerB: "Republika Naroda Kine",
    answerC: "Narodna Republika Kina",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 81,
    question:
      "Snage Koumintanga imale su zadnje uporište na _____ gdje su osnovale Republiku Kinu, zasebnu državu.",
    answerA: "Tajlandu",
    answerB: "Taj Mahalu",
    answerC: "Tajvanu",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 82,
    question: "Koja je bila temeljna svrha Lige naroda?",
    answerA: "poticanje rata",
    answerB: "bogaćenje Amerike",
    answerC: "ravnopravnost država",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 83,
    question: "Gdje je bilo sjedište Lige naroda?",
    answerA: "u Genovi",
    answerB: "u Ženevi",
    answerC: "u Beču",
    correctAnswer: "B",
    difficulty: 1,
  },
];

