interface questionListItem {
  id: number;
  question: string;
  answerA: string;
  answerB: string;
  answerC: string;
  correctAnswer: string;
  difficulty: number;
}

export const questionList: Array<questionListItem> = [
  {
    id: 0,
    question: "Koje je točno ime pisca „Mjerenje svijeta“?",
    answerA: "Daniel Kehlman",
    answerB: "Daniel Kelhman",
    answerC: "Daniel Kehlmann",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 1,
    question:
      "Kada je Gauss otišao na kongres prirodoslovaca u Berlinu na početku knjige?",
    answerA: "U rujnu 1828.",
    answerB: "U svibnju 1829.",
    answerC: "U prosincu 1830.",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 2,
    question: "Kako se zove Gaussov sin iz drugog braka? ",
    answerA: "Edward",
    answerB: "Eugen",
    answerC: "Elliot",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 3,
    question: "Koje je puno ime drugog glavnog lika u knjizi?",
    answerA: "Alexandar van Humboldt",
    answerB: "Alexander von Humboldt",
    answerC: "Alexandar von Humbolt",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 4,
    question:
      "Prije koliko je godina Humboldt išao u svoju ekspediciju (gledano od kongresa prirodoslovaca)?",
    answerA: "28",
    answerB: "30",
    answerC: "25",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 5,
    question: "Priča o kojem čovjeku je Humboldta inspirirala na putovanje?",
    answerA: "Aguirrea Mahnitog",
    answerB: "Jacksona Hrabrog",
    answerC: "Nattiera Snažnog",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 6,
    question: "Nakon kojeg događaja su se malom Humboldtu poboljšale ocjene?",
    answerA: "Pada u jezero",
    answerB: "Tatine kazne",
    answerC: "Promjene učitelja",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 7,
    question:
      "Na kojem su sveučilištu studirali Humboldt i njegov stariji brat?",
    answerA: "Sveučilištu u Berlinu",
    answerB: "Sveučilištu u Hamburgu",
    answerC: "Sveučilištu u Frankfurtu",
    correctAnswer: "C",
    difficulty: 2,
  },
  {
    id: 8,
    question: "Je li Humboldt bio na vjenčanju svoga brata?",
    answerA: "Da",
    answerB: "Ne",
    answerC: "Nije rečeno",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 9,
    question:
      "Kako se zove teorija o nastajanju Zemljine kore koja se spominje u romanu?",
    answerA: "nepotunizam",
    answerB: "neptunizam",
    answerC: "nepotizam",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 10,
    question:
      "Što je po službenoj tituli bio Humboldt kad je završio Akademiju?",
    answerA: "Pravnik",
    answerB: "Rudarski tehničar",
    answerC: "Savjetnik u Ministarstvu",
    correctAnswer: "C",
    difficulty: 2,
  },
  {
    id: 11,
    question: "Na koju je Galvanijevu knjigu Humboldt jednom slučajno nabasao?",
    answerA: "o izmjeničnoj struji",
    answerB: "o struji i žabama",
    answerC: "o jednostaničnim organizmima",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 12,
    question: "Tko je spasio Humboldta kad se onesvijestio u rudniku?",
    answerA: "Andreas del Rio",
    answerB: "njegov sluga",
    answerC: "Abraham Werner",
    correctAnswer: "A",
    difficulty: 3,
  },
  {
    id: 13,
    question: "Kakav je stroj konstruirao Humboldt u mjesec dana?",
    answerA: "generator",
    answerB: "tkalački stan",
    answerC: "respiratorni stroj",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 14,
    question: "Tko je bio Kunth?",
    answerA: "majordom",
    answerB: "savjetnik Humboldtovog oca",
    answerC: "Humboldtov učitelj",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 15,
    question: "Od čega je umrla Humboldtova majka?",
    answerA: "gripe",
    answerB: "sušice",
    answerC: "ospica",
    correctAnswer: "B",
    difficulty: 2,
  },
  {
    id: 16,
    question: "Gdje je na svojem putovanju Humboldt prvo došao?",
    answerA: "Weimar",
    answerB: "Berlin",
    answerC: "Essen",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 17,
    question: "Gdje je Humboldt godinu dana vježbao za put?",
    answerA: "Frankfurt",
    answerB: "Salzburg",
    answerC: "Beč",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 18,
    question:
      "Dok je Humboldt boravio u Salzburgu, koju su mjernu jedinicu nazvali?",
    answerA: "Metar",
    answerB: "Volt",
    answerC: "Mol",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 19,
    question: "Kako se zove mladić s kojim je Humboldt krenuo u Španjolsku?",
    answerA: "Arnold Bell",
    answerB: "Aime Bonpland",
    answerC: "Ajohn Beards",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 20,
    question:
      "Koji je ministar vladao u Madridu kad su Humboldt i Bonpland došli?",
    answerA: "Manuel de Urquijo",
    answerB: "Oscar Valverde",
    answerC: "Aritz Carbonero",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 21,
    question: "Što je ministar u Madridu zatražio od Humboldta?",
    answerA: "dijamant",
    answerB: "sredstvo za potenciju",
    answerC: "putovnicu",
    correctAnswer: "O",
    difficulty: 2,
  },
  {
    id: 22,
    question: "Što je Bonpland dobio na brodu?",
    answerA: "groznicu",
    answerB: "vodene kozice",
    answerC: "skorbut",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 23,
    question: "Što je Gaussov otac rekao, tko nikada ne sjedi pogrbljeno?",
    answerA: "Francuz",
    answerB: "Nijemac",
    answerC: "Englez",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 24,
    question:
      "Na koji način je osmogodišnji Gauss zbrojio brojeve od 1 do 100?",
    answerA: "Nije uspio",
    answerB: "Zbrajanjem jednog po jednog",
    answerC: "Gaussovom dosjetkom",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 25,
    question:
      "Kako se zvao Buttnerov asistent koji je s malim Gaussom svaki tjedan radio matematiku?",
    answerA: "Joseph Swift",
    answerB: "Martin Bartels",
    answerC: "Mario Kruger",
    correctAnswer: "B",
    difficulty: 2,
  },
  {
    id: 26,
    question:
      "Gaussova formula za izračunavanje čega se upotrebljavala u cijeloj Njemačkoj?",
    answerA: "Datuma Uskrsa",
    answerB: "Cijene najma",
    answerC: "Udaljenosti planeta",
    correctAnswer: "A",
    difficulty: 3,
  },
  {
    id: 27,
    question:
      "Pilatre je ispravio malog Gaussa da se u balonu na vrući zrak ne leti, nego da se?",
    answerA: "putuje",
    answerB: "plovi",
    answerC: "vozi",
    correctAnswer: "C",
    difficulty: 3,
  },
  {
    id: 28,
    question: "Što Gauss uvijek čini kad je nervozan?",
    answerA: "Moli",
    answerB: "Broji proste brojeve",
    answerC: "Krši prste",
    correctAnswer: "B",
    difficulty: 2,
  },
  {
    id: 29,
    question:
      "Što je riba napravila guvernerovu nećaku u rijeci u Novoj Andaluziji?",
    answerA: "Odgrizla mu tri prsta",
    answerB: "Ugrizla ga za gležanj",
    answerC: "Odgrizla mu ruku",
    correctAnswer: "A",
    difficulty: 3,
  },
  {
    id: 30,
    question:
      "Između čega navodno postoji kanal kojeg Humboldt i Bonpland planiraju otkriti?",
    answerA: "Madeire i Amazone",
    answerB: "Orinoca i Amazone",
    answerC: "Jurua i Amazone",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 31,
    question:
      "Kojoj su nebeskoj pojavi Humboldt i Bonpland svjedočili u Novoj Andaluziji?",
    answerA: "Aurori Borealis",
    answerB: "Pomrčini Sunca",
    answerC: "Pomrčini Mjeseca",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 32,
    question: "Koji je zub brijač izvadio Gaussu?",
    answerA: "kutnjak",
    answerB: "sjekutić",
    answerC: "umnjak",
    correctAnswer: "A",
    difficulty: 3,
  },
  {
    id: 33,
    question: "Što znači „summa cum laude“?",
    answerA: "S najvećim dosegom",
    answerB: "S velikim uspjehom",
    answerC: "S najvećim pohvalama",
    correctAnswer: "C",
    difficulty: 2,
  },
  {
    id: 34,
    question: "Gdje je Gauss pomogao kad mu je ponestalo novaca?",
    answerA: "Pri geodetskom mjerenju",
    answerB: "Vojvodi na posjedu",
    answerC: "Na sveučilištu",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 35,
    question: "Koje je Gaussovo ime?",
    answerA: "Carl Franz Gauss",
    answerB: "Carl Fjodor Gauss",
    answerC: "Carl Friedrich Gauss",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 36,
    question: "Kako se zove Gaussovo životno djelo?",
    answerA: "Disquisitiones Arithmeticae",
    answerB: "Mathematica Universalis",
    answerC: "Diophantine Equations",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 37,
    question: "Kako se zove djevojka koju je Gauss dvaput zaprosio?",
    answerA: "Johanna",
    answerB: "Sally",
    answerC: "Josephine",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 38,
    question: "Kakav je otrov htio popiti Gauss?",
    answerA: "Kumarin",
    answerB: "Kurare",
    answerC: "Cijanid",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 39,
    question: "Što je napalo Humboldta i Bonplanda na planini La Sille?",
    answerA: "Skupina orlova",
    answerB: "Vepar",
    answerC: "Roj dlakavih pčela",
    correctAnswer: "C",
    difficulty: 3,
  },
  {
    id: 40,
    question:
      "Kako se zvao kastiljanski plemić koji je dočekao Humboldta, Bonplanda i veslače na kopnu?",
    answerA: "Don Ignacio",
    answerB: "Don Bartolomeo",
    answerC: "Don Diego",
    correctAnswer: "A",
    difficulty: 3,
  },
  {
    id: 41,
    question: "Kome Humboldt piše pisma tijekom svoje ekspedicije?",
    answerA: "Majci",
    answerB: "Bratu",
    answerC: "Ocu",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 42,
    question: "Gdje su Humboldt i Bonpland prešli magnetni ekvator?",
    answerA: "San Carlos",
    answerB: "Ember Ridge",
    answerC: "Misthaven",
    correctAnswer: "A",
    difficulty: 3,
  },
  {
    id: 43,
    question:
      "Kako se zove putnik iz Saksonije kojeg su sreli Humboldt i Bonpland?",
    answerA: "Schroeder",
    answerB: "Mayer",
    answerC: "Brombacher",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 44,
    question: "Zbog koje je znanosti Gauss postao slavan?",
    answerA: "Antropologije",
    answerB: "Astronomije",
    answerC: "Kemije",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 45,
    question:
      "U Gaussovo vrijeme, onaj tko je proširio vidike matematike bio je kuriozitet. Što je kuriozitet?",
    answerA: "zanimljivost",
    answerB: "junak",
    answerC: "znanstvenik",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 46,
    question: "Kako se zvao asteroid čiju je putanju Gauss odredio?",
    answerA: "Pallas",
    answerB: "Juno",
    answerC: "Ceres",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 47,
    question: "Gauss je od vojvode dobio ponudu da bude upravitelj čega?",
    answerA: "sveučilišta",
    answerB: "zvjezdarnice",
    answerC: "ministarstva",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 48,
    question: "Kako se zvao jedini student koji je Gaussu položio oba ispita?",
    answerA: "Moebius",
    answerB: "Zenon",
    answerC: "Dante",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 49,
    question: "Kako se zove Gaussov najstariji sin?",
    answerA: "Peter",
    answerB: "Joseph",
    answerC: "Timmothy",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 50,
    question: "Kako se zove Gaussova kćer?",
    answerA: "Wilhelmine",
    answerB: "Henriette",
    answerC: "Elisabeth",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 51,
    question:
      "Koji su svjetski rekord u najvećoj nadmorskoj visini postigli Humboldt i Bonpland?",
    answerA: "14320 stopa",
    answerB: "16580 stopa",
    answerC: "18690 stopa",
    correctAnswer: "C",
    difficulty: 2,
  },
  {
    id: 52,
    question:
      "Što je grofovo Gauss trebao srušiti da bi dobio slobodan pogled do mjerne točke?",
    answerA: "staju",
    answerB: "stabla i šupu",
    answerC: "dio kuće",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 53,
    question: "Tko je bila Gaussova druga žena, Minna?",
    answerA: "njegova susjeda",
    answerB: "njegova prijateljica",
    answerC: "Joannina najbolja prijateljica",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 54,
    question:
      "Kako se zove reporter koji je dočekao Humboldta u Novoj Španjolskoj?",
    answerA: "Gomez",
    answerB: "Sergio",
    answerC: "Jose",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 55,
    question: "Kako svi nazivaju Bonplanda, što njemu jako smeta?",
    answerA: "Humboldtov suradnik",
    answerB: "Humboldtov asistent",
    answerC: "Humboldtov radnik",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 56,
    question:
      "Koliko je ljudi bilo žrtvovano za posvećenje hrama kod glavnog trga u Cuernavaci?",
    answerA: "20 tisuća",
    answerB: "15 tisuća",
    answerC: "10 tisuća",
    correctAnswer: "A",
    difficulty: 2,
  },
  {
    id: 57,
    question: "Gdje je Humboldt opovrgnuo neptunizam?",
    answerA: "Planina Cottleleche",
    answerB: "Vulkan Jorull",
    answerC: "Brdo Dolem",
    correctAnswer: "B",
    difficulty: 2,
  },
  {
    id: 58,
    question: "S kojim se američkim predsjednikom našao Humboldt?",
    answerA: "John Adams",
    answerB: "James Monroe",
    answerC: "Thomas Jefferson",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 59,
    question: "Kakvo je mišljenje Napoleon imao o Humboldtu i Bonplandu?",
    answerA: "Volio ih je",
    answerB: "Mrzio ih je",
    answerC: "Nije znao za njih",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 60,
    question: "Što je osnovao Humboldtov brat poslije rata?",
    answerA: "Sveučilište",
    answerB: "Vojna jedinica",
    answerC: "Istražiteljski kompleks",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 61,
    question: "Kamo je Humboldt otputovao pred kraj knjige?",
    answerA: "Peru",
    answerB: "Rusija",
    answerC: "Sjeverna Amerika",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 62,
    question: "U koju se znanost upustio Gauss pred kraj knjige?",
    answerA: "Nautika",
    answerB: "Kemija",
    answerC: "Fizika",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 63,
    question:
      "Kako se zvao fizičar iz Hallea s kojim je poslije surađivao Gauss?",
    answerA: "Weber",
    answerB: "Smith",
    answerC: "Tony",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 64,
    question: "Koliko je djece ima Gauss?",
    answerA: "5",
    answerB: "4",
    answerC: "6",
    correctAnswer: "B",
    difficulty: 2,
  },
  {
    id: 65,
    question: "Koji dragi kamen je našao dječak u rudniku u Rusiji?",
    answerA: "Rubin",
    answerB: "Safir",
    answerC: "Dijamant",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 66,
    question: "Što je lama u Rusiji zamolio Humboldta?",
    answerA: "Da mu oživi psa",
    answerB: "Da prevede svezak",
    answerC: "Da opiše put",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 67,
    question: "Što je kniks?",
    answerA: "vrsta biljke",
    answerB: "poklon pred kim",
    answerC: "mjerni instrument",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 68,
    question: "Koju je lentu car uručio Humboldtu pred kraj knjige?",
    answerA: "Red kralja Jurja",
    answerB: "Red svetog Pavla",
    answerC: "Red svete Ane",
    correctAnswer: "C",
    difficulty: 2,
  },
  {
    id: 69,
    question: "Koliko je dugo Humboldt putovao Rusijom?",
    answerA: "19 tjedana",
    answerB: "17 tjedana",
    answerC: "23 tjedna",
    correctAnswer: "C",
    difficulty: 1,
  },
  {
    id: 70,
    question: "Gdje je završio Bonpland?",
    answerA: "U kućnom pritvoru",
    answerB: "Ubijen je",
    answerC: "Živi u Parizu",
    correctAnswer: "A",
    difficulty: 1,
  },
  {
    id: 71,
    question: "Kamo se uputio Eugen na samom kraju knjige?",
    answerA: "Engleska",
    answerB: "Amerika",
    answerC: "Španjolska",
    correctAnswer: "B",
    difficulty: 1,
  },
  {
    id: 72,
    question: "Kako su se zvali Humboldtovi suputnici u Rusiji?",
    answerA: "Ehrenberg i Rose",
    answerB: "Rose i Becker",
    answerC: "Ehrenberg i Fischer",
    correctAnswer: "A",
    difficulty: 1,
  },
];
